# Generated by Django 3.0 on 2020-07-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_text', models.CharField(help_text='Check Once everything is written', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_text', models.CharField(default='', help_text="Write in correct format. for ex: 'class 6'. It is shown in everywhere", max_length=10, unique=True)),
                ('confirm_grade_text', models.CharField(default='', help_text='Confirm grade', max_length=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Program')),
            ],
        ),
    ]
